# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: '工作记录'
    url: '' #在当前页面跳转至id为works的地方
    weight: 1
  - name: '实验室工作记录'
    parent: '工作记录'
    url: 'works/research' #在当前页面跳转至id为works的地方
    weight: 1
  - name: '私人工作记录'
    parent: '工作记录'
    url: 'works/myself' #在当前页面跳转至id为works的地方
    weight: 2
  - name: '工作记录总览'
    parent: '工作记录'
    url: 'works/all' #在当前页面跳转至id为works的地方
    weight: 3



  - name: '增材制造'
    url: '3dprint'
    weight: 2


  - name: '摄影作品'
    url: 'photos'
    weight: 3


  - name: '演示文档'
    url: 'demo'
    weight: 4
